package runner

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/SaintMaximov/gosigfmt/internal/config"
)

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func TestWalk_Basic(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a.go"), "package p\n")
	writeFile(t, filepath.Join(root, "b.go"), "package p\n")
	writeFile(t, filepath.Join(root, "vendor", "v.go"), "package v\n")
	writeFile(t, filepath.Join(root, "sub", "c.go"), "package p\n")

	cfg := config.Defaults()
	files, err := walk([]string{root + "/..."}, cfg)
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(files)
	want := []string{
		filepath.Join(root, "a.go"),
		filepath.Join(root, "b.go"),
		filepath.Join(root, "sub", "c.go"),
	}
	sort.Strings(want)
	if len(files) != len(want) {
		t.Errorf("want %d files, got %d (%v)", len(want), len(files), files)
	}
}

func TestWalk_SkipTestFiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a.go"), "package p\n")
	writeFile(t, filepath.Join(root, "a_test.go"), "package p\n")

	cfg := config.Defaults()
	cfg.FormatTestFiles = false
	files, err := walk([]string{root + "/..."}, cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || filepath.Base(files[0]) != "a.go" {
		t.Errorf("want only a.go, got %v", files)
	}
}

func TestWalk_SkipGenerated(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a.go"), "package p\n")
	writeFile(t, filepath.Join(root, "gen.go"), "// Code generated by foo. DO NOT EDIT.\n\npackage p\n")

	cfg := config.Defaults()
	files, err := walk([]string{root + "/..."}, cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || filepath.Base(files[0]) != "a.go" {
		t.Errorf("want only a.go, got %v", files)
	}
}
